awesomedata/apd-core

core/Government/Canada.yml

---
version: 1.0
temporal:
spatial:
copyrights:
specification:
language: en
publisher:
organization:
sources:
references:

Simplify URL

---

core/Government/Italy.yml

---
title: Italy
homepage: https://www.dati.gov.it/
description: Il Portale dati.gov.it è il catalogo nazionale dei metadati relativi ai dati rilasciati in formato aperto dalle pubbliche amministrazioni italiane. Il Portale è promosso dal Governo Italiano e gestito dall’Agenzia per l’Italia digitale con il supporto di FormezPA.
version:
keywords:
image:
temporal:
spatial:
copyrights:
specification:
language: it
license:
publisher:
- name: AgID - Agenzia per l'Italia Digitale
web: http://www.agid.gov.it/
organization:
- name: AgID - Agenzia per l'Italia Digitale
web: http://www.agid.gov.it/
issued_time:
sources:
references:

Added link to public open data from the Italian government.

---

core/Sports/Tennis-database-of-rankings-results-and-stats-for-WTA.yml

---
version: 1.0
temporal:
spatial:
copyrights:
specification:
language: en
publisher:
organization:
sources:
references:

Added WTA (Women's Tennis Association) yml

---

deploy/index.mako

---
version: 1.0
temporal:
spatial:
copyrights:
specification:
language: en
publisher:
organization:
sources:
references:

#14: fix fixme link error

---

core/Government/Toronto-ON-Canada.yml

---
title: Toronto-ON-Canada
homepage: https://portal0.cf.opendata.inter.sandbox-toronto.ca/
description: 
version: 1.0
keywords: 
image: 
temporal:
spatial:
copyrights:
specification:
data_quality: true
language: en

Fix Toronto-ON-Canada.yml

---

core/Government/Houston-TX-US.yml

---
version: 1.0
temporal:
spatial:
copyrights:
specification:
language: en
publisher:
organization:
sources:
references:

Fix Houston, TX dataset - rename file to match

---

core/SocialSciences/Humanitarian-Data-Exchange.yml

As requested, correct the source YAML for Humanitarian Data Exchange

---

core/Energy/Smart Meter Data Portal.yml

---
title: Smart Meter Data Portal
homepage: https://smda.github.io/smart-meter-data-portal
category: Energy
description: The Smart Meter Data Portal is part of the National Science Foundation (NSF) Smart Grid Data Analytics Spoke Project, providing researchers a platform to access public data sets related to smart meter.
version: 1.0
keywords: power, energy, smart meter
image:
temporal:
spatial:
copyrights:
accrual_periodicity: rolling release
specification:
data_quality: true
language: en
license: Varies
publisher:
organization:
issued_time: 2018.04
sources:
references:

Create Smart Meter Data Portal.yml

---

core/NaturalLanguage/German-Political-Speeches-Corpus.yml

---
version: 1.0
temporal:
spatial:
copyrights:
specification:
language: en
publisher:
organization:
sources:
references:

Natural language resource added: German political speeches

---

core/Government/NYC-Open-Data.yml

---
version: 1.0
temporal:
spatial:
copyrights:
specification:
language: en
publisher:
organization:
sources:
references:

updated NYC open data url

---

core/PublicDomains/Microsoft-Research-Open-Data

Added Microsoft Research Open Data beta

added MS Research Open Data @ PublicDomains

---

core/NaturalLanguage/Worldtree-Explanation-Corpus.yml

---
version: 1.0
temporal:
spatial:
copyrights:
specification:
language: en
publisher:
organization:
sources:
references:

Added WorldTree explanation corpus

---

core/Biology/Stanford-Microarray-Data.yml

Reverts awesomedata/apd-core#57

Revert "update a few URL's"

---

core/Biology/PubGene-now-Coremine-Medical.yml

homepage: https://www.coremine.com/

Changed homepage from PubGene to Coremine Medical

---

core/Government/Ukraine.yml

---
title: Ukraine
homepage: https://data.gov.ua/
description:
version:
keywords:
image:
temporal:
spatial:
access_level:
copyrights:
specification:
language:
license:
publisher:
organization:
issued_time:
sources: []

Add Government/Ukraine data source

---

core/PublicDomains/GrandComics.yml

---
version: 1.0
temporal:
spatial:
copyrights:
specification:
language: en
publisher:
organization:
sources:
references:

Added Grand Comics Database

---

core/Government/everycrsreport.yml

U.S. Congressional Research Service Reports

Add US CRS report data

---

core/Healthcare/i2b2.yml

Add i2b2 NLP datasets to Healthcare section.

Add i2b2 NLP datasets.

---

core/ImageProcessing/DukeMTMC-Data-Set.yml
core/ImageProcessing/HumanEva-Dataset.yml

---
title: DukeMTMC Data Set
homepage: http://vision.cs.duke.edu/DukeMTMC/
description: DukeMTMC aims to accelerate advances in multi-target multi-camera tracking. It provides a tracking system that works within and across cameras, a new large scale HD video data set recorded by 8 synchronized cameras with more than 7,000 single camera trajectories and over 2,000 unique identities, and a new performance evaluation method that measures how often a system is correct about who is where.
version: 1.0
keywords: person detection, multi-tracking, multi-camera
image: http://vision.cs.duke.edu/DukeMTMC/img/dataset.jpg
temporal:
spatial:
copyrights:
specification: …

DukeMTMC added

---

core/SocialNetworks/Reddit-Comments.yml

update to pushshift.io for reddit comments.
---
title: Reddit Comments
homepage: http://files.pushshift.io/reddit/comments/
description:
version:
keywords:
image:
temporal:
spatial:
access_level:
copyrights:
specification:
language:
license:
publisher:
organization:
issued_time:
sources: []

Update Reddit-Comments URL 

---

core/Transportation/NYC-Taxi-Trip-Data-2009.yml
core/Transportation/U.S.-Bureau-of-Transportation-Statistics-BTS.yml

Fix redirected NYC and BTS links

Fix redirected NYC and BTS links

---

core/Climate+Weather/Dutch-Weather.yml
core/Transportation/Dutch-Traffic-Information.yml

---
version: 1.0
temporal:
copyrights:
specification:
language: en
publisher:
- name: …

Add Dutch Weather under Climate and Weather

---

core/TimeSeries/3W-dataset-rare-undesirable-real-events-in-oil-wells.yml

Please, consider this contribution.
---
version: 1.0
temporal:
copyrights:
specification:
language: en …

3W-dataset-rare-undesirable-real-events-in-oil-wells in TimeSeries

---

core/Biology/UniGene.yml

Update UniGene URL to the downloads section

Update UniGene URL

---

core/Government/Istanbul-Municipality-Open-Data.yml

Adding Istanbul Municipality Open Data Portal under Government

Add Istanbul Metropolitan Municipality open data portal

---

core/Agriculture/Hyperspectral-Benchmark-Dataset-On-Soil-Moisture.yml
core/Agriculture/U.S.-Department-of-Agricultures-PLANTS-Database.yml
core/Biology/1000-Genomes.yml
core/Biology/American-Gut-Microbiome-Project.yml
core/Biology/Broad-Bioimage-Benchmark-Collection-BBBC.yml
core/Biology/Cell-Image-Library.yml
core/Biology/Complete-Genomics-Public-Data.yml
core/Biology/EBI-ArrayExpress.yml
core/Biology/EBI-Protein-Data-Bank-in-Europe.yml
core/Biology/ENCODE-project.yml
core/Biology/Electron-Microscopy-Pilot-Image-Archive-EMPIAR.yml
core/Biology/Gene-Expression-Omnibus-GEO.yml
core/Biology/Harvard-Medical-School-LINCS-Project.yml
core/Biology/Human-Genome-Diversity-Project.yml
core/Biology/Human-Microbiome-Project-HMP.yml
core/Biology/ICOS-PSP-Benchmark.yml
core/Biology/NCBI-Taxonomy.yml
core/Biology/NCI-Genomic-Data-Commons.yml
core/Biology/OpenSNP-genotypes-data.yml
core/Biology/Protein-Data-Bank.yml
core/Biology/Psychiatric-Genomics-Consortium.yml
core/Biology/PubChem-Project.yml
core/Biology/PubGene-now-Coremine-Medical.yml
core/Biology/Sanger-Catalogue-of-Somatic-Mutations-in-Cancer-COSMIC.yml
core/Biology/Sequence-Read-ArchiveSRA.yml
core/Biology/Systems-Science-of-Biological-Dynamics-SSBD-Database.yml
core/Biology/The-Catalogue-of-Life.yml
core/Biology/The-Personal-Genome-Project.yml
core/Biology/Universal-Protein-Resource.yml

Hi @ppival I went through data under Agriculture and Biology topics and added descriptions to the ones I could find a description for.

Add descriptions to data under Agriculture and Biology topics.

---

.gitignore
tools/check_urls.py
tools/requirements.txt

@ppival this script checks homepage urls of all yml files and creates a report of urls with issues. Script catches connection errors, timeouts, redirects , SSL errors and others.
To use it:
```
cd tools
pip install -r requirements.txt
python check_urls.py
```
This will create `check_urls.csv` file.

Create check urls script

---

core/Biology/rfam.yml

Add Rfam dataset under Biology

---

core/SearchEngines/DomainsProject.yml

Domains project - Sorted list of Internet domains (>50 million atm)

Added Domains Project dataset under SearchEngines category

---

core/SocialNetworks/Covid19-40-Million-Tweets.yml

Hello. This adds 40+ million tweets related to COVID-19 dataset to social networks.

Add Covid-19 tweets to social networks

---

core/Economics/Long-Term-Productivity-Database.yml

Hi, this adds Long-Term Productivity Database under Economics

Add Long-Term Productivity Database

---

core/ImageProcessing/SVIRO.yml

Hi all,
I create a pull request to add a dataset we created and made publicly available to the community.
Thanks a lot in advance!
Best regards,
Steve

Add SVIRO under ImageProcessing

---

core/Healthcare/Aws-COVID-19.yml

Hi, this adds AWS Covid-19 datasets to healthcare category

Add AWS covid-19 datasets to Healthcare

---

Agriculture/Optimized Soil Adjusted Vegetation Index

title: Optimized Soil Adjusted Vegetation Index
homepage: https://www.indexdatabase.de/db/i-single.php?id=63
category: Agriculture
description: The IDB is a tool for working with remote sensing indices. It provides a quick overview of which indices are usable for a specific sensor and a specific topic. There is no such tool available at the moment as far as we know, despite the necessity to have a more structured overview of current research results in the area of remote sensing indices.
version: 1.0
keywords: remote sensing, agriculture, soil intelligence

Optimized Soil Adjusted Vegetation Index

---

core/GIS/Database-of-Continents-Coutries-States-Cities.yml

---
title: Database of all continents, countries, States/Subdivisions/Provinces and Cities
homepage: https://www.back4app.com/database/back4app/list-of-all-continents-countries-cities
category: GIS
description: Database with all the continents, countries, states, and cities of the world. This directory contains all 7 continents, 250 countries, and more than 127 thousand cities. All data can be downloaded or retrieved and managed via APIs
version: 1.0

Add Database-of-Continents-Countries-States-Cities under GIS

---

core/MachineLearning/Audi-Autonomous-Driving-Dataset.yml

Add Audi autonomous driving dataset under machine learning

Add Audi autonomous driving dataset

---

core/Healthcare/Yahoo-COVID-19.yml

Add Yahoo Knowledge Graph COVID-19 Datasets to healthcare

Add Yahoo Knowledge Graph COVID-19 Datasets

---

core/Healthcare/Covid-Tracking-Project.yml

Add Covid Tracking Project data under healthcare

Add Covid Tracking Project data

---

core/ProstateCancer/Prostate-R.yml

The PDF linked to in the  previous commit is no longer online. The dataset is part of a famous book 'Elements of Statistical Learning' by Hastie, Tibshirani and Friedman.
---
version: 1.0
temporal:
spatial: …

Correct 1 fixme-Link to Prostate-R

---

core/Government/Iowa.yml

Add Iowa data portal to Government

Add Iowa data portal to government

---

core/Agriculture/Global-dataset-of-historical-yields-for-major-crops.yml

Add global dataset of historical yields for major crops 1981–2016 to agriculture

Add global dataset of historical yields for major crops

---

core/Sports/NFL-play-by-play.yml

Add NFL play-by-play data under sports

Add NFL play-by-play data

---

core/Government/New-York-Department-of-Sanitation.yml

Add NY Department of Sanitation monthly tonnage data under Government

Add NY Department of Sanitation data

---

core/Agriculture/Global-dataset-of-historical-yields-for-major-crops.yml
core/Government/New-York-Department-of-Sanitation.yml
core/Sports/NFL-play-by-play.yml

These 3 files did not have correct YML syntax in their description fields. This fixes those.

Update descriptions for correct YML syntax

---

core/ImageProcessing/MV-ROI.yml

A dataset for multi-view region of interest prediction

add mv roi dataset

---

core/Biology/Palmer-Penguins.yml

Adding Palmer Penguins data under Biology

Add palmer penguins data

---

deploy/index.mako

Added 2 CV dataset lists to Complementary collection

add cv dataset collections

---

core/Government/US-Counties.yml

Add US Counties data under Government

Add US counties data under government

---

core/Healthcare/COVID-19-Case-Surveillance-Public-Use-Data.yml

Add COVID-19 Case Surveillance Public Use Data

Add COVID-19 public use data

---

core/Energy/SYND.yml

---
version: 1.0
temporal:
copyrights:
specification:
language: en
publisher:
- name: …

Add SYND under energy

---

core/Government/Vietnam.yml

Statistical data portal from Vietnam government.

Add Vietnam under Government

---

core/Agriculture/Lemon-Dataset.yml
core/Energy/SYND.yml

---
title: Lemons quality control dataset
homepage: https://github.com/softwaremill/lemon-dataset
category: Agriculture
description: Lemon dataset has been prepared to investigate the possibilities to tackle the issue of fruit quality control. It contains 2690 annotated images (1056 x 1056 pixels)
version: 1.0.0
keywords: fruit, quality, lemon, segementation
image: https://github.com/softwaremill/lemon-dataset/blob/master/docs/img/lemon-dataset-annotated-sprite.png
language: en
license: MIT
organization:
- name: SoftwareMill
web: https://softwaremill.com/
issued_time: 2020.07

Lemon dataset

---

core/Climate+Weather/Washington Post Climate Change.yml

Add Washington Post climate change data under Climate+Weather

Add Washington Post climate change data

---

core/Finance/BIS Statistics.yml

Add BIS Statistics data to Finance

Add BIS Statistics

---

core/NaturalLanguage/Dirty-Words.yml

Add dirty words data under Natural Language

Add dirty words data

---

core/Civil/Mass-Mobilization-Data-Project.yml
core/SocialSciences/Mass-Mobilization-Data-Project.yml

Hi, this adds Mass Mobilization Data under Social Sciences

Add Mass Mobilization data

---

core/SocialSciences/Authoritarian-Ruling-Elites.yml

This adds Authoritarian Ruling Elites Database under Social Sciences

Add Authoritarian Ruling Elites Database

---

core/SocialNetworks/China-Biographical-Database.yml

Add China Biographical Database under Social Networks

Add China Biographical Database

---

core/Government/Debt-to-penny.yml

Add Debt to Penny dataset

---

core/EarthScience/Global-Wind-Atlas.yml

Add Global Wind Atlas to Earth Science

Add Global Wind Atlas

---

core/SocialNetworks/Facebook-Social-Connectedness-Index.yml

Add Facebook Social Connectedness Index

Add Facebook Social Connectedness Index

---

core/ImageProcessing/Newspaper-Navigator.yml

Add Newspaper Navigator

---

core/Government/Jail-deaths-in-America.yml

Add Jail deaths in America

---

core/Sports/Equity-in-Athletics.yml

Add Equity in Athletics

---

core/Museums/Metropolitan-Museum-of-Art-Collection-API.yml

Add Metropolitan-Museum-of-Art-Collection-API under museums

---

core/CyberSecurity/Traffic-and-Log-Data-Captured-During-a-Cyber-Defense-Exercise.yml

Add CyberSecurity category and Traffic and Log Data Captured During a Cyber Defense Exercise data

Add cyber defense exercise data

---

core/Healthcare/COVID-19-Reported-Patient-Impact-and-Hospital-Capacity-by-Facility.yml

Add COVID-19 Reported Patient Impact data

Add COVID-19 Reported Patient Impact data

---

core/SocialSciences/World-Inequality-Database.yml

Add world inequality database

---

core/ImageProcessing/Cube-Plus-Plus.yml
deploy/index.mako
deploy/requirements.txt
tests/requirements.txt

Hi! Two small commits
1. Looks like Travis updates are [broken](https://travis-ci.org/github/awesomedata/apd-core/jobs/744710995) because of [two](https://github.com/awesomedata/apd-core/blob/master/core/Museums/Metropolitan-Museum-of-Art-Collection-API.yml) [ds](https://github.com/awesomedata/apd-core/blob/master/core/Climate%2BWeather/German-Meteorological-Service-CDC.yml) without desription. Trying to fix that.
2. Slightly updating PyYAML version, as 3.12 is imcompatible with [UDEC](https://github.com/awesomedata/apd-core/blob/master/core/Energy/UDEC.yml) yaml

Fix no-description bug

---

core/Entertainment/TwitchStreamersData.yml

I have added a folder for data sets from entertainment industry. There is a lot of data regarding Youtube, Hollywood, etc. out there and i think adding it to the repo would be beneficial. I have also added a data set to the folder for the top twitch streamers of the past year.

Made a new folder and dataset

---

core/MachineLearning/Tik-Tok-Dataset.yml

---
version: 1.0
temporal:
copyrights:
specification:
language: en
publisher:
- name: …

Tik Tok Dataset contributed

---

core/Finance/SEC-EDGAR.yml

---
title: SEC EDGAR
homepage: https://www.sec.gov/edgar/about
category: Finance
description: EDGAR, the Electronic Data Gathering, Analysis, and Retrieval system, is the primary system for companies and others submitting documents under the Securities Act of 1933, the Securities Exchange Act of 1934, the Trust Indenture Act of 1939, and the Investment Company Act of 1940. Containing millions of company and individual filings, EDGAR benefits investors, corporations, and the U.S. economy overall by increasing the efficiency, transparency, and fairness of the securities markets. The system processes about 3,000 filings per day, serves up 3,000 terabytes of data to the public annually, and accommodates 40,000 new filers per year on average.
version: 1.0
keywords: Finance, Finacial, Markets, …

Added SEC-EDGAR dataset under Finance

---

core/ImageProcessing/DAVID.yml

Add dataset for semantic segmentation on videos

add DAVID dataset

---

core/SocialNetworks/Clubhouse-Dataset.yml

Add Clubhouse-Dataset under SocialNetworks
---
title: Clubhouse Dataset
homepage: https://www.kaggle.com/johntukey/clubhouse-dataset

Add Clubhouse-Dataset under SocialNetworks

---

core/GIS/Shadow-Accrual-Maps.yml

Adding Shadow Accrual Maps dataset from https://github.com/VIDA-NYU/shadow-accrual-maps/

Add Shadow-Accrual-Maps under GIS

---

core/Energy/MORED.yml

---
version: 1.0
temporal:
copyrights:
specification:
language: en
publisher:
- name: …

Add MORED under Energy

---

core/Biology/BCNB.yml

```yaml
title: BCNB
homepage: https://bupt-ai-cz.github.io/BCNB/
category: Biology
description: There are WSIs of 1058 patients, part of tumor regions are annotated in WSIs. Except for the WSIs, we have also provided the clinical data of each patient, which includes age, tumor size, tumor type, ER, PR, HER2, HER2 expression, histological grading, surgical, Ki67, molecular subtype, number of lymph node metastases, and ALN status.
version:
keywords: breast, image classification, multi-modal, clinical characteristics
image: https://raw.githubusercontent.com/bupt-ai-cz/bupt-ai-cz/main/imgs/BCNB-logo.png
temporal:
spatial: 
access_level: 
copyrights: https://github.com/bupt-ai-cz/BALNMP#license
specification:
data_quality:
language:
license: …
```

Add BCNB under Biology

---

core/SocialSciences/Fragile-States-Index.yml

---
version: 1.0
temporal:
copyrights:
specification:
language: en
publisher:
- name: …

refactor: update url to suggested in the old page

---

core/ComputerNetworks/Coveo-Shopper-Intent-Prediction.yaml

---
title: Shopper Intent Prediction from Clickstream E‑Commerce Data with Minimal Browsing Information
homepage: https://github.com/coveooss/shopper-intent-prediction-nature-2020
category: ComputerNetworks
...

Add Coveo-Shopper-Intent-Prediction under ComputerNetworks

---

core/SocialNetworks/The-Reddit-COVID-Dataset.yml

Add The Reddit COVID Dataset, accessible [here](https://socialgrep.com/datasets/the-reddit-covid-dataset).

Add The Reddit COVID Dataset

---

core/PublicDomains/Stack-Overflow-Annual-Developer-Survey.yml

---
version: 1.0
temporal:
copyrights:
specification:
language: en
publisher:
- name: …

Add Stack-Overflow-Annual-Developer-Survey under PublicDomains

---

APO.yml
ASEAN Stats.yml
Asian KLEMS.yml
Atlas Economic Complexity.yml
BIS Financial Database.yml
Barro Lee.yml
CEPII Database.yml
EUKLEMS.yml
Historical National Accounts.yml
LA KLEMS.yml
Maddison Project.yml
NTA.yml
Penn World Table.yml
World Input-Output Database.yml
World KLEMS.yml

The additional dataset includes Asian Productivity (APO), Barro-Lee dataset, EUKLEMS, Asian KLEMS, Latin America KLEMS, World KLEMS, Historical NA, Project Maddison, National Transfer Accounts, Penn World Table, World Input-Output Database, BIS Financial Database, ASEAN Stats.

Update several important datasets for Economics

---

core/Neuroscience/The_Nencki-Symfonia_EEG_ERP_dataset.yml

---
version: 1.0
temporal:
copyrights:
specification:
language: en
publisher:
- name: …

The Nencki-Symfonia dataset

---

.github/workflows/deploy.yaml

Add cleanse up

---

core/Biology/Serratus-Open-Virome.yml

Serratus is a public-domain collection of RNA viruses detected via sequence alignment across 7.1 million public sequencing datasets (~28 petabytes of raw data). The flat collection of raw data is available in the data lake as well as systematic access via SQL.
This data can be cross-referenced to meta-data available in the public `Sequence Read Archive` dataset via the `run_id` identifier, and the `BioSamples` database via the `biosample` identifier. ~40% of the viruses have associated geo-spatial coordinates, all the samples contain data publication dates (temporal).
A main link to the ["Accessing Data" page](https://github.com/ababaian/serratus/wiki/Access-Data-Release) may be more appropriate than the [front-end splash page](https://serratus.io). Will take feedback on how to improve …

Serratus Open Virome Dataset

---

core/Biology/ANHIR.yml
core/Biology/CIMA.yml

superseded https://github.com/awesomedata/awesome-public-datasets/pull/421

ANHIR & CIMA

---

core/Climate+Weather/Open-Meteo.yml

Open-Meteo is an Open-Source Weather API utilising open-data weather models including `NOAA GFS`, `DWD ICON`, `Canadian Meteorological Centre GEM`, `MeteoFrance Arome & Arpege` and others. With the additional weather reanalysis models like `Copernicus ERA5`, up to 80 years of past weather data are available. By combining ERA5 with IPCC climate models, downscaled climate forecasts up to the year 2050 are available with 10 km resolution.
All data is available as open-access under `CC BY 4.0` with source code under `AGPL-3.0`. All sources, attributions and licences are thoroughly listed to make data access as transparent as possible.
API Documentation is available here https://open-meteo.com/en/docs
```
---
title: Open-Meteo - Open-Source Weather API
homepage: https://open-meteo.com …
```

Add Open-Meteo to Climate+Weather

---

core/Government/Brazil.yml

The old link was wrong so I updated to the correct link

Update Brazil.yml 404 link

---

core/SocialSciences/Inter-American-Development-Bank-Open-Data.yml

under social sciences
---
version: 1.0
temporal:
copyrights:
specification:
language: en
license: Apache …

Add Inter-American Development Bank
