core/Government/Ghent-Belgium.yml
pointed to https://data.stad.gent/datasets instead of https://data.stad.gent/data
---
version: 1.0
temporal:
spatial:
copyrights:
specification:
language: en
publisher:
organization:
sources:
references:
=> Point to right url

core/Government/Luxembourg.yml
---
version: 1.0
temporal:
spatial:
copyrights:
specification:
language: en
publisher:
organization:
sources:
references:
=> Add Luxembourgish Open Data portal

core/Energy/Global Power Plant Database.yml
Add the Global Power Plant Database
http://datasets.wri.org/dataset/globalpowerplantdatabase
Visualize the Global Power Plant Database on Resource Watch
http://goo.gl/XMyMLt
---
title: Global Power Plant Database
homepage: http://datasets.wri.org/dataset/globalpowerplantdatabase
category: Energy
description: The Global Power Plant Database is a comprehensive, open source database of power plants around the world. It centralizes power plant data to make it easier to navigate, compare and draw insights. Each power plant is geolocated and entries contain information on plant capacity, generation, ownership, and fuel type. As of April 2018, the database includes around 25,500 power plants from 162 countries. It will be continuously updated as data becomes available. 
version: 1.0.0
keywords: …
=> Add Global Power Plant Database

core/Software/source{d}-Public-Git-Archive.yml, core/Software/source{d}-source-code-identifiers.yml
* Public Git Archive
* Source Code Identifiers
Signed-off-by: egor <egor@sourced.tech>
---
title: Public Git Archive
homepage: https://github.com/src-d/datasets/tree/master/PublicGitArchive
category: Software
description: a Big Code dataset for all – dataset of 182,014 top-bookmarked Git repositories from GitHub
version:
keywords: source code, git, GitHub, software repositories, development history, open dataset
image:
temporal:
spatial:
access_level:
copyrights:
specification:
language:
license:
publisher:
organization:
issued_time:
sources: []
---
title: Source Code Identifiers
homepage: https://github.com/src-d/datasets/tree/master/Identifiers
category: Software
description: 41.7 million distinct splittable identifiers collected …
=> Add 2 new datasets to Software section:

core/Education/Student-Data-from-Free-Code-Camp.yml
All the data of freecodecamp is available on github
---
title: Student Data from Free Code Camp
homepage: https://github.com/freeCodeCamp/open-data
category: Education
description:
version:
keywords:
image:
temporal:
spatial:
access_level:
copyrights:
specification:
language:
license:
publisher:
organization:
issued_time:
sources: []
=> Updated the link of data from freecodecamp

core/GIS/Global-Administrative-Areas-Database-GADM.yml
The actual URL does not have a www prefix (and this is now
relevant when served over https).
Add some metadata after a brief click-through.
=> Fix URL and add more metadata

core/Software/GHTorrent.yml
---
title: GHTorrent
homepage: ghtorrent.org
category: Software
description: Scalable, queriable, offline mirror of data offered through the Github REST API.
version: 1.0
keywords: github, open source
image: https://pbs.twimg.com/profile_images/580387012341010432/LpYCqgLJ_400x400.png
temporal:
spatial:
copyrights:
specification:
language: en
license: CC-BY-SA-4.0
publisher:
- name: Georgios Gousios
web: http://gousios.org/
organization:
issued_time: 2013.05
sources:
- name: GitHub
access_url: https://github.com
references:
- title: The GHTorrent dataset and tool suite
reference: http://dl.acm.org/citation.cfm?id=2487085.2487132
=> Add GHTorrent

core/EarthScience/NERRS-SWMP.yml
With 'www.nerrsdata.org' in the file, the link in Awesome Public Datasets went to 'https://github.com/awesomedata/awesome-public-datasets/blob/master/www.nerrsdata.org'
So I updated it to 'http://nerrsdata.org'. I *think* this should work...
=> update nerrs-swmp to http instead of www

core/SocialSciences/Humanitarian-Data-Exchange.yml
---
title: Humanitarian Data Exchange
homepage: https://data.humdata.org/
category: SocialSciences
description: The Humanitarian Data Exchange (HDX) is an open platform for sharing data, launched in July 2014. The goal of HDX is to make humanitarian data easy to find and use for analysis. Our growing collection of datasets has been accessed by users in over 200 countries and territories. Watch this video to learn more.
A team within the United Nations Office for the Coordination of Humanitarian Affairs (OCHA) manages HDX. OCHA is part of the United Nations Secretariat, responsible for bringing together humanitarian actors to ensure a coherent response to emergencies. The HDX team includes OCHA staff and a number of consultants. We are based in North America, Europe and Africa.
version: …
=> Updated to working link

core/ComputerNetworks/P2P-Trace-Archive.yml
---
title: The Peer-to-Peer Trace Archive
homepage: http://p2pta.ewi.tudelft.nl/
category: ComputerNetworks
description: Real-world measurements play a key role in studying the characteristics and improving the design of Peer-to-Peer (P2P) systems. Although many P2P measurements have been carried out in the last decade, few traces are publicly accessible, and the available traces are available online in different formats. This situation hampers researchers in exchanging, studying, and reusing existing traces. As a result, many P2P studies have been based on unrealistic assumptions about the characteristics of P2P systems, and many P2P algorithms and methods still lack a realistic evaluation.
To address this situation, we build the Peer-to-Peer (P2P) Trace Archive, which is designed as a …
=> Add P2P-Trace-Archive

core/Neuroscience/NeuroMorpho.yml
Added NeuroMopho.org dataset: an inventory of digitally reconstructed neurons associated with peer-reviewed publications.
=> added NeuroMorpho

core/Agriculture/Hyperspectral-Benchmark-Dataset-On-Soil-Moisture.yml, core/GIS/GRSS-DASE-Website.yml
**1. Hyperspectral benchmark dataset on soil moisture**
homepage: https://doi.org/10.5281/zenodo.1227837
**2. IEEE Geoscience and Remote Sensing Society DASE Website**
homepage: http://dase.ticinumaerospace.com
=> Add Soil Moisture Dataset and GRSS DASE database

core/NaturalLanguage/Noisy-Speech.yml
---
title: Noisy speech database for training speech enhancement algorithms and TTS models
homepage: https://datashare.is.ed.ac.uk/handle/10283/2791
category: NaturalLanguage
description: Clean and noisy parallel speech database. The database was designed to train and test speech enhancement methods that operate at 48kHz. A more detailed description can be found in the papers associated with the database.
version:
keywords: Noisy, TTS
image: 
temporal:
spatial:
access_level:
copyrights:
specification:
data_quality:
language: en
license: 
publisher:
- name: Edinburgh DataShare
web: https://datashare.is.ed.ac.uk
organization:
- name:
web:
issued_time:
sources:
- name:
access_url:
references:
- title:
reference:
=> added Noisy-Speech.yml

core/ImageProcessing/Danbooru-Tagged-Anime-Illustration-Dataset.yml
---
title: Danbooru Tagged Anime Illustration Dataset
homepage: https://www.gwern.net/Danbooru
description: A large-scale anime image database with 3.33m+ images annotated with 99.7m+ tags; it can be useful for machine learning purposes such as image recognition and generation.
=> Add danbooru dataset

core/Software/source{d}-pull-request-review-comments.yml
* PR review comments
* Size: 1.5GB
* Description: 25.3 million GitHub PR review comments since January 2015 till December 2018.
Signed-off-by: egor <egor@sourced.tech>
=> Add dataset of Pull Request review comments

core/SocialSciences/Titanic-Survival-Data-Set.yml
Update the link address redirected to Kaggle:
This dataset was downloaded from public Web. https://www.kaggle.com/c/titanic/data
I saved this data in the repository as backup because I felt this data is valuable and not widely found on the Web.
Please refer to the original license of the dataset.
=> Update titanic survival data

core/ImageProcessing/OpenImagesByGoogle.yml
---
title: Open Images From Google
homepage: https://storage.googleapis.com/openimages/web/download.html
description: Pictures with segmentation masks for 2.8 million object instances in 350 categories.
version: V5
keywords:
image:
temporal:
spatial:
access_level:
copyrights:
specification:
language:
license:
publisher: Google
organization:
issued_time: 2019-05-08
sources:
- name: Announcing Open Images V5 and the ICCV 2019 Open Images Challenge
access_url: https://ai.googleblog.com/2019/05/announcing-open-images-v5-and-iccv-2019.html
=> Add open images v5

core/SocialNetworks/United-States-Congressional-Twitter-Data.yml
---
title: CongressTweets
homepage: https://github.com/alexlitel/congresstweets
description: Daily datasets with tweets of 1100+ accounts associated with the House of Representatives and Senate, including members, committees, and more.
keywords: congress, twitter, us politics
image: 
temporal:
spatial:
copyrights:
accrual_periodicity: Daily
specification:
language: en
license: MIT
publisher:
- name: 
web: 
organization:
- name:
web: 
issued_time:
sources:
- name: 
access_url: 
references:
- title: 
reference:
=> Add congressional twitter dataset

core/Sports/Pro_Kabadi_season1_7.yml
Data Set of Pro Kabadi league Match by Match Details data is collected through Web Scraping. hope content is useful for data analysis and match winning predictions.
---
title: Pro Kabadi season 1 to 7
homepage: https://github.com/ranganadhkodali/Pro-Kabadi-season-1-7-Stats
category: Sports
description: Pro Kabadi League is a professional-level Kabaddi league in India. Data Set contains the match level stats from the seasion 1 to 7. data set include player level stats and match level stats including points earned and key match events.
version: 1.0
keywords: Pro Kabadi,ProKabadi,Kabadi,Sports DataSet,indian sports
image: https://www.prokabaddi.com/static-assets/images/cssimages/prokabaddi-logo.png
temporal:
copyrights: …
=> Add ProKabadi Seasion 1 to 7 Sports Data Set

core/eSports/opendota-dump.yml
Greetings. This adds the OpenDota data dump from 2016, contains data about over a million dota 2 matches. In the page linked, minor versions of the dataset are available for download (4GB), as well as (much) bigger datasets (150+GB) hosted by [academictorrents.com](https://blog.opendota.com/2017/03/24/datadump2/).
IMHO it makes sense to put it under a new category but let me know otherwise.
Cheers.
---
title: OpenDota data dump
homepage: https://blog.opendota.com/2017/03/24/datadump2/
category: eSports
description:
version:
keywords: Dota 2
image:
temporal:
spatial:
access_level:
copyrights:
specification:
language:
license:
publisher:
organization:
issued_time:
sources: []
=> Add OpenDota data dump

core/Government/OpenDataSofts-list-of-1600-open-data.yml
The previous link was dead (redirected to the homepage) since the blog post was republished. I added its new URL instead.
=> Update dead link

core/Education/New-York-State-Education-Department.yml
Hi, I added New York State Education Data under Education topic. Here is the yml file:
```
---
title: New York State Education Department Data
homepage: https://data.nysed.gov/downloads.php
category: Education
description: The New York State Education Department (NYSED) is committed to making data available and easy to use. This site provides a first step in publicly reporting educational data so all interested parties can be better informed as they work to advance student achievement.
version:
keywords: higher education, school, county, district
image:
temporal:
spatial:
access_level:
copyrights:
specification:
language: en
license:
publisher:
- name:
web:
organization:
- name: New York State Education Department
web: …
```
=> Add New York State Education Department Data under Education

core/Energy/UK-DALE.yml
Closes #148
---
version: 1.0
temporal:
copyrights:
specification:
language: en …
=> Fix link to UK-DALE.

core/Energy/DEL.yml
Added Domestic Electrical Load datasets for South Africa (1994 - 2014). Research use only (non-commercial).
=> Add DEL to Energy

core/Transportation/U.S.-National-Highway-Traffic-Safety-Administation-Fatalities-since-1975.yml
Added U.S. National Highway Traffic Safety Administration Fatality Analysis Reporting System traffic crash data since 1975.
=> Add NHTSA FARS dataset

core/Energy/PEM1.yml
---
title: PEM1
homepage: https://github.com/ECSIM/pem-dataset1
category: Energy
description: Proton Exchange Membrane (PEM) Fuel Cell Dataset
version:
keywords:
image:
temporal:
spatial:
access_level:
copyrights:
specification:
language:
license:
publisher:
organization:
issued_time:
sources: []
=> Add PEM1 under energy

core/Healthcare/COVID-19-Johns-Hopkins.yml
Hi. This adds Johns Hopkins COVID-19 dataset to healthcare.
=> Add Johns Hopkins COVID-19 dataset to healthcare

core/Healthcare/COVID-19-New-York-Times.yml
This adds New York Times covid data under healthcare.
=> Add New York Times covid-19 data

core/TimeSeries/Turing-Change-Point-Dataset.yml
Hi there,
We recently created a dataset for developing and evaluating change point detection algorithms, I thought you might be interested in adding it to your list.
```yaml
---
title: Turing Change Point Dataset
homepage: https://github.com/alan-turing-institute/TCPD
category: TimeSeries
description: Contains 42 annotated time series collected for the development and evaluation of change point detection algorithms.
version: 1.0
keywords: change point detection, time series analysis, benchmark dataset
image:
temporal:
spatial:
copyrights:
specification:
data_dictionary: true
language: en
license: MIT License
publisher:
- name: Gertjan van den Burg
web: https://gertjan.dev
- name: Chris Williams
web: …
```
=> TimeSeries dataset for change point detection

core/SocialNetworks/Donald-Trump-Twitter-Screenshots.yml
---
title: 43k+ Donald Trump Twitter Screenshots
homepage: https://pikaso.me/blog/trump-twitter-archive
description: This archive contains screenshots of 43,475 Donald Trump tweets from May 2009 to May 2020.
version: 1.0
keywords: donald trump, twitter, screenshot
image:
temporal:
spatial:
copyrights: Copyright https://pikaso.me
specification:
language: en
license: CC BY 4.0
publisher:
- name: Pikaso
web: https://pikaso.me
organization:
- name: Pikaso
web: https://pikaso.me
issued_time: 2020.06
sources:
- name:
access_url:
references:
- title:
reference:
=> Add Donald-Trump-Twitter-Screenshots under SocialNetworks

tests/validate.py
I realized we have the build failing icon on the front page. Looks like it was failing due to  
> ./tests/validate.py:30: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
This fixes that issue
=> Fix tests by specifcying loader

core/Software/GHTorrent.yml
Use the full URL for ghtorrent so that the link doesn't 404 in the generated markdown. Closes https://github.com/awesomedata/awesome-public-datasets/issues/388.
=> Fix ghtorrent link

core/eSports/fifa2021.yml
---
title: FIFA-2021 Complete Player Dataset
homepage: https://www.kaggle.com/aayushmishra1512/fifa-2021-complete-player-data
category: eSports
description:
version:
keywords: FIFA-2021
image:
temporal:
spatial:
access_level:
copyrights:
specification:
language:English
license:
publisher:
organization:
issued_time:
sources: []
=> Created FIFA-2021 in eSports

core/ImageProcessing/CCAgT.yml
---
title: 'Cytology Dataset – CCAgT: Images of Cervical Cells with AgNOR Stain Technique'
homepage: https://arquivos.ufsc.br/d/373be2177a33426a9e6c/
description: 'The dataset contains 2540 images (1600x1200 where each pixel is 0.111μm×0.111μm) from three different slides, having at least one nucleus per image. These images are from fields belonging to a sample cervical slide, colored with silver-stained, a method known as Argyrophilic Nucleolar Organizer Regions (AgNOR). These images were manually labeled with "objects" of four categories: Nuclei, Clusters, Satellites and Out of Focus. This annotation is available in COCO format, and in images masks.'
version: 1.1
keywords: Cytology, AgNOR, image segmentation, object detection, semantic segmentation.
image: …
=> ADD Cytology Dataset - CCAgT: Images of Cervical Cells with AgNOR Stain Technique under ImageProcessing

core/NaturalLanguage/German-Political-Speeches-Corpus.yml
The link "German Political Speeches Corpus - Collection of political speeches from [...]" currently goes to https://github.com/awesomedata/awesome-public-datasets/blob/master/purl.org/corpus/german-speeches on https://github.com/awesomedata/awesome-public-datasets/blob/master/README.rst.
This PR changes it to go to http://adrien.barbaresi.eu/corpora/speeches/, which redirects from https://purl.org/corpus/german-speeches.
=> Fix German Political Speeches Corpus broken link

core/Agriculture/Global-dataset-of-historical-yields-for-major-crops.yml, core/Agriculture/Lemon-Dataset.yml, core/Biology/ICOS-PSP-Benchmark.yml, core/Climate+Weather/Dutch-Weather.yml, core/EarthScience/NERRS-SWMP.yml, core/EarthScience/Oil-and-Gas-Authority-UK.yml, core/Economics/The-Center-for-International-Data.yml, core/GIS/TZ-Timezones-shapfiles.yml, core/Government/Metropolitain-Transportation-Commission-MTC-California-US.yml, core/Government/Missisauga-ON-Canada.yml, core/Healthcare/Yahoo-COVID-19.yml, core/ImageProcessing/Adience-Unfiltered-faces-for-gender-and-age-classification.yml, core/ImageProcessing/SVIRO.yml, core/Neuroscience/NeuroMorpho.yml, core/Software/GHTorrent.yml, core/Software/source{d}-source-code-identifiers.yml, core/Sports/Pro_Kabadi_season1_7.yml
There are a few typos in the descriptions, as well as some minor grammar fixes which were fixed in this PR. The filenames which have typos are unchanged (e.g. `Missisauga-ON-Canada.yml`).
=> Fix typos in descriptions

core/PublicDomains/Ably.yml
Adds Ably Hub, open source of realtime data from any sector to PublicDomains.
=> Add Ably Open Realtime Data under PublicDomains

core/ImageProcessing/Cube-Plus-Plus.yml
Hi!
We've collected a new dataset of 4890 raw Canon images with a SpyderCube color target in right bottom angle, see https://github.com/Visillect/CubePlusPlus for details.
Hope it will be usefull for the community. 
---
title: Cube++
homepage: https://github.com/Visillect/CubePlusPlus
description: 4890 raw 18-megapixel images, each containing a SpyderCube color target in their scenes, manually labelled categories, and ground truth illumination chromaticities. The dataset was collected for illumination estimation problem.
version: 2.0
keywords: Color Constancy, Illumination Estimation, White Balance, Multiple Illumination, Mixed Illumination
image: https://github.com/Visillect/CubePlusPlus/blob/master/description/examples.jpg
temporal: 2014-2020
spatial: 2592*1728 …
=> Cube++ added

core/MachineLearning/Iranis.yml
---
version: 1.0
temporal:
copyrights:
specification:
language: en
publisher:
- name: …
=> Add Iranis dataset

core/Energy/DBFC.yml
---
title: DBFC
homepage: https://github.com/ECSIM/dbfc-dataset
category: Energy
description: Direct Borohydride Fuel Cell (DBFC) Dataset
version:
keywords:
image:
temporal:
spatial:
access_level:
copyrights:
specification:
language:
license:
publisher:
organization:
issued_time:
sources: []
=> Add DBFC under energy

core/Government/Berkeley-CA-Open-Data.yml
---
title: City of Berkeley Open Data
homepage: https://data.cityofberkeley.info/
=> Add City of Berkeley Open Data under government

core/ImageProcessing/ETH_Entomological_Collection_Fine_Grained_Butterfly_Images.yml
---
title: ETH Entomological Collection (ETHEC) Fine Grained Butterfly (Lepidoptra) Images
homepage: https://doi.org/10.3929/ethz-b-000365379
description: 
version:
keywords: fine grained image classification, multi-label classification, image classification, hierarchical labels, lepidoptra, butterflies, natural images
image: 
temporal:
spatial: 
copyrights:
specification:
data_quality:
language: en
license: IN COPYRIGHT - NON-COMMERCIAL USE PERMITTED
publisher:
organization:
issued_time: 
sources: []
references:
=> Add ETHEC dataset under ImageProcessing

core/SocialNetworks/2021_Portuguese_Elections_Twitter_Dataset_57M_tweets_1M_users.yml
---
title: 2021 Portuguese Elections Twitter Dataset - 57M+ tweets, 1M+ users 
homepage: https://github.com/msramalho/election-watch/blob/master/datasets/01_portuguese_presidential_elections_2021_01_24.md
description: This dataset contains 57.155.221 tweets and 1.115.491 users mostly from the Portuguese Twittersphere, collected from Sep 2nd 2020 to Jan 30 2021 (151 days). The watched users stem from a seed of political accounts and news sources. The dataset further contains 1857 suspended users, along with their time_suspended and time_unsuspended in case of reactivations. 
version: 1.0
keywords: twitter, elections, politics, portugal
image:
temporal:
spatial:
copyrights:
specification: …
=> Add new dataset under SocialNetworks

core/Healthcare/Medal-medical-abbreviations.yml
---
title: MeDAL - A large medical text dataset curated for abbreviation disambiguation
homepage: https://github.com/BruceWen120/medal
category: Healthcare
description: Medical Dataset for Abbreviation Disambiguation for Natural Language Understanding (MeDAL) is a large medical text dataset curated for abbreviation disambiguation, designed for natural language understanding pre-training in the medical domain. It was published at the ClinicalNLP workshop at EMNLP.
version:
keywords: healthcare, medicine, nlp, abbreviations
image: https://raw.githubusercontent.com/BruceWen120/medal/master/figures/rs_illustration.svg
temporal:
spatial:
copyrights:
specification:
language: en
license: National Library of Medicine …
=> Add the Medal dataset to the Healthcare section

core/CyberSecurity/CCCS-CIC-AndMal-2020.yml
---
version: 1.0
temporal:
copyrights:
specification:
language: en
publisher:
- name: …
=> Added AndMal2020 under CyberSecurity

core/NaturalLanguage/DBpedia.yml
---
title: DBpedia - Structured data from Wikipedia
homepage: https://databus.dbpedia.org/dbpedia/collections/latest-core
category: NaturalLanguage
=> Update DBPedia's core dataset url

CONTRIBUTING.md, core/Education/PISA.yml
---
title: Program for International Student Assessement (PISA)
homepage: https://www.oecd.org/pisa/
category: Education
description: Contains 15-year-old students' performance on reading, math, and science from countries across the globe.
version: 1.0
keywords: global, test, students.
image: https://www.oecd.org/media/oecdorg/satellitesites/pisa/New%20web%20banner_1.png
temporal:
copyrights:
specification:
language: en
license: 
publisher:
- name: 
web: 
organization:
- name: Organization for Economic Cooperation and Development (OECD)
web: https://www.oecd.org/
issued_time: 2019.02
sources:
- name: 
access_url: 
references:
- title: 
reference:
=> Adding PISA dataset

core/MachineLearning/LLVIP.yml
Add LLVIP under MachineLearning 
---
title: LLVIP
homepage: https://bupt-ai-cz.github.io/LLVIP/
category: MachineLearning
description: This dataset contains 30976 images, or 15488 pairs, most of which were taken at very dark scenes, and all of the images are strictly aligned in time and space. Pedestrians in the dataset are labeled. We compare the dataset with other visible-infrared datasets and evaluate the performance of some popular visual algorithms including image fusion, pedestrian detection and image-to-image translation on the dataset.
version: 1.0
keywords: image fusion, pedestrian detection, image-to-image translation.
image: 
temporal:
spatial: 
access_level: 
copyrights: This LLVIP Dataset is made freely available to academic and non-academic entities for non-commercial …
=> Add LLVIP under MachineLearning 

core/Energy/MORED.yml, core/MachineLearning/Fluorescent-Neuronal-Cells.yml
Add [Fluorescent Neuronal Cells dataset](http://amsacta.unibo.it/id/eprint/6706) to MachineLearning category.
This dataset is a collection of 283 images coming from life science experiments. They consist of high-resolution (1200x1600) fluorescent microscopy pictures of neuronal cells and the corresponding ground-truth masks. Possible applications include but are not limited to semantic segmentation, object detection and object counting. 
For more information, please refer to [Morelli, R., Clissa, L. et al., 2021. Automating cell counting in fluorescent microscopy through deep learning with c-ResUnet.](https://rdcu.be/cB1Ds).
*Note: an additional change to `MORED.yml` was required to prevent testing.sh to fail with `RuntimeError: Failed to read YAML data: mapping values are not allowed`
=> Fluorescent Neuronal Cells

core/Healthcare/COVID-19-Ecuador-Data.yml
---
title: Covid-19 non-processed data of Ecuador
homepage: https://github.com/andrab/ecuacovid
category: Healthcare
description: It's a project which provides non-processed datasets about Covid-19 in Ecuador. Data are extracted from official reports by SNGRE, MSP and Registro Civil del Ecuador. All of them are governmental organizations.
version: 1.0
keywords: Covid 19, Ecuador, Ecuacovid, Coronavirus.
image: 
temporal:
spatial: 
copyrights:
specification:
data_quality: true
language: es
license: MIT License
publisher:
- name: 
web: 
organization:
- name: Andrab S.A.
web: 
issued_time: 2021.12
sources:
- name: 
access_url: 
references:
- title: 
reference:
=> Add COVID-19-Ecuador-Data.yml under Healthcare

core/Sports/Transfermarkt-Datasets.yml
```yaml
---
title: Transfermarkt Datasets
homepage: https://github.com/dcaribou/transfermarkt-datasets
category: Sports
description: Clean, structured and automatically updated football (soccer) data from Transfermarkt
version: 1.0
keywords: football, soccer, players, games, matches
image: https://raw.githubusercontent.com/dcaribou/transfermarkt-datasets/master/diagram.png
temporal:
spatial:
copyrights:
accrual_periodicity: weekly
specification:
data_quality: true
language: en
publisher:
- name: dcaribou
web: https://github.com/dcaribou
issued_time: 2022.04.08
sources:
- name: Transfermarkt
access_url: https://www.transfermarkt.com/
```
=> Add Transfermarkt-Datasets under Sports

core/MachineLearning/Biometrically-Filtered-Famous-Figure-Dataset-for-Age-Estimation.yml
---
title: B3FD - Facial age (and gender) estimation dataset with 375k images
homepage: https://github.com/kbesenic/B3FD
category: MachineLearning
description: The B3FD dataset is a publicly available unconstrained facial image dataset for age (and gender) estimation introduced in the paper Picking out the bad apples: unsupervised biometric data filtering for
refined age estimation, consisting of 375,592 facial image samples with corresponding age labels.
version: 1.0
keywords: age estimation, gender estimation, face analysis, web scraping, biometric filtering.
=> Adding the B3FD age estimaton dataset under Machine Learning.

core/Biology/CytoImageNet.yml
---
title: CytoImageNet
homepage: https://www.kaggle.com/stanleyhua/cytoimagenet
category: Biology
description: A large-scale dataset of microscopy images. Contains 890,737 total grayscale images. 894 classes (approx. 1000 images per class). Images belong to 40 openly-available datasets from Recursion, Image Data Resource, Broad Bioimage Benchmark Collection, Kaggle and the Cell Image Library.
version: 1.0
keywords: computer vision, microscopy images, biology, deep learning
image: https://github.com/stan-hua/CytoImageNet/blob/c65f28d6ca27cb7ecb37dfa442576083b5496522/figures/github_images/cytoimagenet_plot.png
temporal:
spatial:
copyrights:
specification:
language: en
license: Public Domain
publisher:
- name: …
=> Add CytoImageNet dataset under Biology

core/NaturalLanguage/Wordbank.yml
---
title: Wordbank
homepage: http://wordbank.stanford.edu/
category: NaturalLanguage
description: Open, de-identified database of vocabulary development from 84,138 children and 93,955 CDI administrations, across 38 languages and 78 instruments. The data managers of this project request that all data be accessed through the R package wordbankr - https://github.com/langcog/wordbankr
version:
keywords: Language development, natural language, linguistics, linguistic research
image: http://wordbank.stanford.edu/static/images/walrus.png
temporal:
copyrights: Unless otherwise stated, Wordbank and its datasets are licensed under a Creative Commons Attribution 4.0 International License/ http://wordbank.stanford.edu/faq#what-is-the-license-for-derivative-works …
=> Add Wordbank dataset under NaturalLanguague

core/NaturalLanguage/NoLanguageLeftBehindNLLB200vo.yml
---
title: No Language Left Behind (NLLB - 200vo)
homepage: https://huggingface.co/datasets/allenai/nllb
category: NaturalLanguage
description: Dataset based on Meta's metadata for mined bitext. Contains word-aligned text in 148 English-centric and 1465 non-English-centric language pairs.
version:
keywords: Natural Language Processing, bitext, word alignment
image: 
temporal:
spatial: 
copyrights: This dataset contains crawled text from multiple sources. Text may be covered by individual copyright and discretion is advised.
specification:
data_quality: Not curated
language: multiple
license: ODC-By v1.0: https://opendatacommons.org/licenses/by/1-0/
publisher: HuggingFace
organization: Allen Institute for AI
issued_time:
sources: …
=> Add No Language Left Behind (NLLB - 200vo) dataset under NaturalLanguage

core/Architecture/appartment-models.yml
---
version: 1.0
temporal:
copyrights:
specification:
language: en
publisher:
- name: …
=> add new 42k appartment model dataset

core/DataChallenges/Netflix-Prize.yml
Previous Netflix Challenge link is now redirecting to Netflix main website
=> Correct deprecated link

core/ImageProcessing/CCAgT.yml
A new version of the dataset is available, so I have updated the version of the dataset as well as its reference link.
---
title: 'Cytology Dataset – CCAgT: Images of Cervical Cells with AgNOR Stain Technique'
homepage: https://doi.org/10.17632/wg4bpm33hj.2
description: 'Contains 9339 images with resolution of 1600×1200 where each pixel is 0.111µmX0.111µm from 15 different slides stained with AgNOR technique, having at least one label per image. Have more than sixty-three thousand annotations. The images from patients of Gynecology and Colonoscopy Outpatient Clinic of the Polydoro Ernani de São Thiago University Hospital of the Universidade Federal de Santa Catarina (HU-UFSC). This research was approved by the UFSC Research Ethics Committee (CEPSH), protocol …
=> Update CCAgT version

core/Psychology+Cognition/Open-Cognitive-Science-Data-Repository.yml
---
title: Open Cognitive Science Data
homepage: https://nivlab.github.io/opendata
category: Psychology+Cognition
description: Pubicly available behavioral datasets from across cognitive science (with a strong focus on learning & decision-making). Maintained by the Niv Lab at Princeton University.
version: 1.0
keywords: cognitive science, cognitive modeling, reinforcement learning, decision making, cognitive control, computational psychiatry
image: false
temporal: true
spatial: false
copyrights:
specification:
language: en
license: MIT license
publisher:
- name:
web:
organization:
- name: Niv Lab, Princeton University
web: https://nivlab.princeton.edu/
issued_time:
sources:
- name:
access_url:
references:
- …
=> Add Open Cognitive Science Data Repository under Psychology+Cognition

core/Transportation/Melbourne-pedestrian-counting.yml
---
title: Melbourne Pedestrian Counting
homepage: https://data.melbourne.vic.gov.au/explore/dataset/pedestrian-counting-system-monthly-counts-per-hour/
category: Transportation
description: This dataset contains hourly pedestrian counts since 2009 from pedestrian sensor devices located across the City of Melbourne. 
version: 1.0
keywords: pedestrian count, foot traffic, pedestrian sensors, covid-19,traffic flow
image: 
temporal:
spatial: 
copyrights:
specification:
data_quality: 
language: en
license: CC BY 4.0
publisher:
- name: 
web: 
organization:
- name: City of Melbourne  
web: https://www.melbourne.vic.gov.au/
issued_time: 2014.05
sources:
- name: 
access_url: 
references:
- title: 
reference:
=> Add Melbourne-pedestrian-counting under Transportation

core/ComputerNetworks/Merklemap-DNS-Records-dataset.yml
---
title: Merklemap DNS records Dataset
homepage: https://www.merklemap.com/dns-records-database
category: ComputerNetworks
description: Contains 4B+ DNS records accross 700 million unique hostnames. Includes A, AAAA, ANAME, CAA, CNAME, HINFO, HTTPS, MX, NAPTR, NS, PTR, SOA, SRV, SSHFP, SVCB, TLSA and TXT entries.
version: 1.0
keywords: 
image: 
temporal:
spatial: 
copyrights:
specification:
data_quality: 
language: 
license: CC BY-NC-SA 4.0
publisher:
- name: Merklemap
web: https://www.merklemap.com/
organization:
issued_time: 
sources:
references:
=> Add Merklemap-DNS-Records-dataset.yml

core/MachineLearning/YaMBDa-5B-Music-Interaction-Dataset.yml
Add Yambda-5B, a Large-Scale Multi-modal Dataset for Ranking And Retrieval.
=> Add Yambda-5B under MachineLearning

core/GIS/map-verse.yml
---
This pull request adds MAP-VERSE to the GIS category.
MAP-VERSE (MAP usability - Validated Empirical Research by Systematic Evaluation) is an open-source metadata repository that indexes and standardizes empirical datasets in map usability and spatial cognition research. The repository provides curated metadata for datasets involving eye tracking, EEG/fMRI, and other human sensing methods collected during geospatial tasks.
- **Homepage:** https://map-verse.github.io/Repository/
- **GitHub Repository:** https://github.com/MAP-VERSE/Repository
- **Category:** GIS
- **License:** MIT
Notes:
MAP-VERSE does not host raw data; instead, it provides standardized metadata and links to external datasets (with DOIs where available). It is intended to support researchers seeking discoverable, …
=> Add MAP-VERSE metadata under GIS

core/Government/UNESCO-Data-Hub.yml
Adding UNESCO's official comprehensive data catalog to the Government category.
- **Homepage**: https://data.unesco.org
- **Description**: UNESCO's official data hub providing authoritative global statistics across education, culture, science, communication, and information domains
- **Formats**: CSV, Excel, JSON, API, Parquet, GeoJSON  
- **Languages**: English, French, Spanish, Arabic
- **Global scope**: Supporting SDG monitoring and evidence-based policymaking
- **Contact**: data.ai@unesco.org
This dataset meets high-quality criteria for academic, research, and educational communities.
=> Add UNESCO Data Hub under Government category
